POST http://localhost:6060/register/authors HTTP/1.1
Content-Type: application/json


{
    "name": "andrea",
    "surname": "Lauro",
    "password": "ciao",
    "email": "giovanni@gmail.com",
    "dob": "28/01/1994",
    "avatar": "https://img.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg?w=2000"
}

#######
POST http://localhost:6060/login/authors HTTP/1.1
Content-Type: application/json


{
    "password": "ciao",
    "email": "giovanni@gmail.com"
    
}